services:
  fideslog:
    image: ethyca/fideslog:local
    command: [ "python", "fideslog/api/main.py" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - fideslog.env
    environment:
      FIDESLOG__SERVER_HOST: "fideslog"
      FIDESLOG__SERVER_HOT_RELOAD: true
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /fideslog
        read_only: False
