########
# Pylint
########
[tool.pylint.messages_control]
disable=[
    "import-error",
    "missing-module-docstring",
    "too-few-public-methods",
    "unsubscriptable-object",
]
extension-pkg-whitelist = "pydantic"
